// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service/tiles/proto/tiles/tiles.proto

package tiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tiles service

type TilesService interface {
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type tilesService struct {
	c    client.Client
	name string
}

func NewTilesService(name string, c client.Client) TilesService {
	return &tilesService{
		c:    c,
		name: name,
	}
}

func (c *tilesService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Tiles.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tiles service

type TilesHandler interface {
	Get(context.Context, *Request, *Response) error
}

func RegisterTilesHandler(s server.Server, hdlr TilesHandler, opts ...server.HandlerOption) error {
	type tiles interface {
		Get(ctx context.Context, in *Request, out *Response) error
	}
	type Tiles struct {
		tiles
	}
	h := &tilesHandler{hdlr}
	return s.Handle(s.NewHandler(&Tiles{h}, opts...))
}

type tilesHandler struct {
	TilesHandler
}

func (h *tilesHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.TilesHandler.Get(ctx, in, out)
}
