// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tiles/tiles.proto

package tiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    int32    `protobuf:"varint,3,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b50a9c166ce25d2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Request) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Request) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Response struct {
	File                 []byte   `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b50a9c166ce25d2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "tiles.Request")
	proto.RegisterType((*Response)(nil), "tiles.Response")
}

func init() { proto.RegisterFile("proto/tiles/tiles.proto", fileDescriptor_7b50a9c166ce25d2) }

var fileDescriptor_7b50a9c166ce25d2 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc9, 0xcc, 0x49, 0x2d, 0x86, 0x90, 0x7a, 0x60, 0x11, 0x21, 0x56, 0x30, 0x47,
	0xc9, 0x98, 0x8b, 0x3d, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x88, 0x87, 0x8b, 0x31, 0x42,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x88, 0x31, 0x02, 0xc4, 0x8b, 0x94, 0x60, 0x82, 0xf0, 0x22,
	0x41, 0xbc, 0x28, 0x09, 0x66, 0x08, 0x2f, 0x4a, 0x49, 0x8e, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x55, 0x48, 0x88, 0x8b, 0xc5, 0x2d, 0x33, 0x27, 0x15, 0xac, 0x94, 0x27, 0x08,
	0xcc, 0x36, 0x32, 0xe4, 0x62, 0x0d, 0x01, 0x99, 0x2e, 0xa4, 0xc1, 0xc5, 0xec, 0x9e, 0x5a, 0x22,
	0xc4, 0xa7, 0x07, 0xb1, 0x19, 0x6a, 0x93, 0x14, 0x3f, 0x9c, 0x0f, 0x31, 0x44, 0x89, 0x21, 0x89,
	0x0d, 0xec, 0x2a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xea, 0x18, 0x20, 0xb0, 0x00,
	0x00, 0x00,
}
