// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/geocoding/proto/geocoding/geocoding.proto

package geocoding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Search struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_1efdda0d446351ea, []int{0}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Coordinates struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_1efdda0d446351ea, []int{1}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Coordinates) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type ForwardResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardResponse) Reset()         { *m = ForwardResponse{} }
func (m *ForwardResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardResponse) ProtoMessage()    {}
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1efdda0d446351ea, []int{2}
}

func (m *ForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardResponse.Unmarshal(m, b)
}
func (m *ForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardResponse.Marshal(b, m, deterministic)
}
func (m *ForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardResponse.Merge(m, src)
}
func (m *ForwardResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardResponse.Size(m)
}
func (m *ForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardResponse proto.InternalMessageInfo

func (m *ForwardResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ReverseResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReverseResponse) Reset()         { *m = ReverseResponse{} }
func (m *ReverseResponse) String() string { return proto.CompactTextString(m) }
func (*ReverseResponse) ProtoMessage()    {}
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1efdda0d446351ea, []int{3}
}

func (m *ReverseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseResponse.Unmarshal(m, b)
}
func (m *ReverseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseResponse.Marshal(b, m, deterministic)
}
func (m *ReverseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseResponse.Merge(m, src)
}
func (m *ReverseResponse) XXX_Size() int {
	return xxx_messageInfo_ReverseResponse.Size(m)
}
func (m *ReverseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseResponse proto.InternalMessageInfo

func (m *ReverseResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Search)(nil), "geocoding.Search")
	proto.RegisterType((*Coordinates)(nil), "geocoding.Coordinates")
	proto.RegisterType((*ForwardResponse)(nil), "geocoding.ForwardResponse")
	proto.RegisterType((*ReverseResponse)(nil), "geocoding.ReverseResponse")
}

func init() {
	proto.RegisterFile("service/geocoding/proto/geocoding/geocoding.proto", fileDescriptor_1efdda0d446351ea)
}

var fileDescriptor_1efdda0d446351ea = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x2c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x4f, 0xcd, 0x4f, 0xce, 0x4f, 0xc9, 0xcc, 0x4b, 0xd7, 0x2f, 0x28,
	0xca, 0x2f, 0xc9, 0x47, 0xe2, 0xc3, 0x59, 0x7a, 0x60, 0x19, 0x21, 0x4e, 0xb8, 0x80, 0x92, 0x1c,
	0x17, 0x5b, 0x70, 0x6a, 0x62, 0x51, 0x72, 0x86, 0x90, 0x08, 0x17, 0x6b, 0x61, 0x69, 0x6a, 0x51,
	0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xa3, 0x64, 0xc8, 0xc5, 0xed, 0x9c, 0x9f,
	0x5f, 0x04, 0x54, 0x9b, 0x58, 0x92, 0x5a, 0x2c, 0x24, 0xc0, 0xc5, 0x9c, 0x93, 0x58, 0x02, 0x56,
	0xc2, 0x14, 0x04, 0x62, 0x82, 0x45, 0xf2, 0xf3, 0x24, 0x98, 0xa0, 0x22, 0xf9, 0x79, 0x4a, 0xda,
	0x5c, 0xfc, 0x6e, 0xf9, 0x45, 0xe5, 0x89, 0x45, 0x29, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x60, 0xad, 0x3c, 0x41,
	0x30, 0x2e, 0x48, 0x71, 0x50, 0x6a, 0x59, 0x6a, 0x51, 0x71, 0x2a, 0x61, 0xc5, 0x46, 0x1d, 0x8c,
	0x5c, 0x9c, 0xee, 0x30, 0xa7, 0x0b, 0x59, 0x71, 0xb1, 0x43, 0xed, 0x11, 0x12, 0xd4, 0x43, 0x78,
	0x11, 0xe2, 0x1d, 0x29, 0x29, 0x24, 0x21, 0x34, 0xe7, 0x28, 0x31, 0x08, 0xd9, 0x73, 0xb1, 0x43,
	0xad, 0x15, 0x12, 0x43, 0x52, 0x88, 0xe4, 0x55, 0x14, 0x03, 0xd0, 0x9c, 0xa8, 0xc4, 0x90, 0xc4,
	0x06, 0x0e, 0x49, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xb3, 0x40, 0x30, 0x7e, 0x01,
	0x00, 0x00,
}
