// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/filecache/proto/filecache/filecache.proto

package filecache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRequest struct {
	HashKey              string   `protobuf:"bytes,1,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHashKey() string {
	if m != nil {
		return m.HashKey
	}
	return ""
}

type GetResponse struct {
	Hit                  bool     `protobuf:"varint,1,opt,name=Hit,proto3" json:"Hit,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetHit() bool {
	if m != nil {
		return m.Hit
	}
	return false
}

func (m *GetResponse) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type SetRequest struct {
	HashKey              string   `protobuf:"bytes,1,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{3}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetHashKey() string {
	if m != nil {
		return m.HashKey
	}
	return ""
}

func (m *SetRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type SetResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=Created,proto3" json:"Created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{4}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type DeleteRequest struct {
	HashKey              string   `protobuf:"bytes,1,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetHashKey() string {
	if m != nil {
		return m.HashKey
	}
	return ""
}

type DeleteResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f676ec37050bf855, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*File)(nil), "filecache.File")
	proto.RegisterType((*GetRequest)(nil), "filecache.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "filecache.GetResponse")
	proto.RegisterType((*SetRequest)(nil), "filecache.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "filecache.SetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "filecache.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "filecache.DeleteResponse")
}

func init() {
	proto.RegisterFile("service/filecache/proto/filecache/filecache.proto", fileDescriptor_f676ec37050bf855)
}

var fileDescriptor_f676ec37050bf855 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x2c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0xcb, 0xcc, 0x49, 0x4d, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x2f, 0x28,
	0xca, 0x2f, 0xc9, 0x47, 0xe2, 0xc3, 0x59, 0x7a, 0x60, 0x19, 0x21, 0x4e, 0xb8, 0x80, 0x92, 0x1e,
	0x17, 0x8b, 0x1b, 0x90, 0x23, 0x24, 0xc4, 0xc5, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0x66, 0x83, 0xc4, 0x5c, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x80, 0x62, 0x3c,
	0x41, 0x60, 0xb6, 0x92, 0x1a, 0x17, 0x97, 0x7b, 0x6a, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71,
	0x89, 0x90, 0x04, 0x17, 0xbb, 0x47, 0x62, 0x71, 0x86, 0x77, 0x6a, 0x25, 0x54, 0x23, 0x8c, 0xab,
	0x64, 0xcc, 0xc5, 0x0d, 0x56, 0x57, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc0, 0xc5, 0xec,
	0x91, 0x59, 0x02, 0x56, 0xc4, 0x11, 0x04, 0x62, 0x82, 0x0c, 0x07, 0x59, 0x0c, 0x33, 0x1c, 0xc4,
	0x56, 0xb2, 0xe2, 0xe2, 0x0a, 0x26, 0xc2, 0x70, 0xac, 0x7a, 0xd5, 0xb9, 0xb8, 0x83, 0x91, 0x2c,
	0x04, 0x6a, 0x76, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x81, 0x5a, 0x0a, 0xe3, 0x2a, 0x69, 0x72,
	0xf1, 0xba, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0x12, 0xf6, 0x84, 0x16, 0x17, 0x1f, 0x4c, 0x29, 0xc2,
	0x58, 0x88, 0x08, 0xdc, 0x58, 0x28, 0xd7, 0xe8, 0x30, 0x23, 0x97, 0x80, 0x1b, 0x2c, 0x58, 0x83,
	0x21, 0x51, 0x22, 0x64, 0xc6, 0xc5, 0x0c, 0x0c, 0x05, 0x21, 0x51, 0x3d, 0x44, 0x0c, 0x20, 0x42,
	0x4f, 0x4a, 0x0c, 0x5d, 0x18, 0x62, 0x89, 0x12, 0x03, 0x48, 0x5f, 0x30, 0x9a, 0xbe, 0x60, 0xec,
	0xfa, 0x82, 0x51, 0xf4, 0xd9, 0x73, 0xb1, 0x41, 0xdc, 0x23, 0x24, 0x81, 0xa4, 0x06, 0xc5, 0xbb,
	0x52, 0x92, 0x58, 0x64, 0x60, 0x06, 0x24, 0xb1, 0x81, 0x13, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0x77, 0x10, 0x8b, 0x55, 0x02, 0x00, 0x00,
}
