name: CI

on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Hadolint
        run: |
          docker run --rm -i hadolint/hadolint < ./service/Dockerfile
          docker run --rm -i hadolint/hadolint < ./service/rsyslog/Dockerfile

      - name: fmt
        run: go fmt ./...

      - name: vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'

  testing:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Unittests
        run: go test -covermode=atomic ./...

  building:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["api", "filecache", "geocodign", "rsyslog", "tiles"]
    name: Build
    steps:
      - uses: actions/checkout@v1
      - name: Build ${{ matrix.service}}
        run: docker build -t chronark/charon-${{ matrix.service}} -f ./service/Dockerfile --build-arg SERVICE=${{ matrix.service}} .
     