name: Release

on:
  push:
    branches:
      - master

jobs:
  publish_services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["api", "filecache", "geocoding", "tiles"]
    name: publish services
    steps:
      - uses: actions/checkout@v2
  
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chronark/charon/${{ matrix.service }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./service/Dockerfile
          buildargs: SERVICE=${{ matrix.service }}

  publish_rsyslog:
    runs-on: ubuntu-latest
    name: publish rsyslog
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chronark/charon/rsyslog
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./Dockerfile