name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["api", "filecache", "geocoding", "rsyslog", "tiles"]
    name: publish
    steps:
      - uses: actions/checkout@v1
  
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chronark/charon/${{ service }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./service/Dockerfile
          buildargs: SERVICE=${{ service }}
